backend:
  name: github
  repo: suresh-kumara-gist/biothermica-site-hs-18-feb-2026
  branch: main
  base_url: https://suresh-issue-82.dcycleproject.org/
  auth_endpoint: /auth/github/repo/6995f009f3f9aacf96d58e5f

media_folder: "sites/biothermica.com/files"
public_folder: "/sites/biothermica.com/files"

collections:
  - name: "pages_en"
    label: "Pages (English)"
    folder: "."
    extension: "html"
    format: "frontmatter"
    create: false
    delete: false
    slug: "{{slug}}"
    filter:
      field: "lang"
      value: "en"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Content (HTML)", name: "body", widget: "text" }

  - name: "pages_fr"
    label: "Pages (Français)"
    folder: "fr"
    extension: "html"
    format: "frontmatter"
    create: false
    delete: false
    slug: "{{slug}}"
    filter:
      field: "lang"
      value: "fr"
    fields:
      - { label: "Titre", name: "title", widget: "string", required: false }
      - { label: "Contenu (HTML)", name: "body", widget: "text" }

editor:
  preview: false

